-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgyzr4X5NHHhuzpZO4
2pNbsNiPVu6K7aDpMmbpaaKr9J+gCgYIKoZIzj0DAQehRANCAARGLcUN1k6hahC0
XwZqtuRzgQccrTlLyYj++WtLGpVudY2ngLmxqM4EUfRQTH1Rbs0e45PPULwMszlB
fV4AjC05
-----END PRIVATE KEY-----